### ISSUE TITLE
First experience: it should be easier and more intuitive to build the solution

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/extensions-samples#159]
Hello everyone!

I am currently working on a talk about Aspire. I do want to mention all the new features in .NET 8 (https://github.com/dotnet/runtime/issues/78518), ASP.NET and dotnet/extensions.

I found this repo in one of the internal issues and decided to see if I could reuse some of the demos.

The first thing I did was cloning the repo, opening the solution in VS and hitting Build via Ctrl+Shift+B.

This has failed:

![image](https://github.com/dotnet/extensions-samples/assets/6011991/b57da80a-5301-417a-8a37-cdc00f61f757)

Then I found the `build.cmd` script and run it. Everything built just fine. I got back to VS to realize that I still can not build and run from VS.

So I decided to run the project from command line:

```cmd
dotnet run --project .\src\Diagnostics\ExceptionSummarization\Microsoft.Extensions.ExceptionSummarization.Sample.csproj
```

And got an error:

```cs
Unable to run your project
Your project targets multiple frameworks. Specify which framework to run using '--framework'
```

So I went to the .csproj file hoping that tfm will be listed there:

![image](https://github.com/dotnet/extensions-samples/assets/6011991/65368d25-6af9-4983-8659-4660cf36508b)

It's not. I know that there must be some `.props` file that defines it somewhere. I also know what `start-vs.cmd` is. The whole process is even documented (which is great 👍). The problem is that all these things are typical to the way we work at Microsoft. If this repo is targeting real-world end users it should avoid any custom solutions. Clone->Open in VS->Build should just work assuming that I have .NET 8 SDK installed and working internet connection. 

Thanks!

**Comment by RussKie** [comment]
Like many .NET repos you can't just open the solution by double clicking on sln file. You need to use https://github.com/dotnet/extensions-samples/blob/main/start-vs.cmd.
You can find more build instructions here: https://github.com/dotnet/extensions-samples/blob/main/docs/building.md.

**Comment by adamsitnik** [comment]
What makes this repo different than https://github.com/dotnet/eShop which makes it possible?

**Comment by RussKie** [comment]
Closing as resolves. Please let me know if you have any further questions or suggestions.
